#!/bin/sh
set -e

todo=${TODOFILE}
if [[ -z $todo ]]; then
    todo=$HOME/todo.txt
fi

task=$(task list-not-done | fzf)

#task=$(cat ${todo} | grep -v @done | fzf)
taskid=$(echo "${task}" | awk '{print $1}')
id=$(tail -n1 ${todo} | awk '{print $1+1}')

echo "${id} $(date -Iseconds) @done(${taskid})" >> ${todo}
